#ifndef Mario_h
#define Mario_h

#include <Arduino.h>

const unsigned short SKY_COLOR = 0x000E;

const unsigned short _MASK = 0xf81f;

const unsigned short RED = 0xF801;
const unsigned short SKIN = 0xfd28;
const unsigned short SHOES = 0xC300;
const unsigned short SHIRT = 0x7BCF;
const unsigned short HAIR = 0x0000;


// 'mario-idle', 13x16px
const uint16_t MARIO_IDLE [] PROGMEM = {
	_MASK, _MASK, _MASK, RED, RED, RED, RED, RED, RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, RED, 
	RED, RED, RED, RED, RED, RED, RED, RED, RED, _MASK, _MASK, _MASK, HAIR, HAIR, HAIR, SKIN, 
	SKIN, HAIR, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, HAIR, SKIN, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, 
	SKIN, SKIN, SKIN, _MASK, _MASK, HAIR, SKIN, HAIR, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, SKIN, SKIN, 
	SKIN, _MASK, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN, HAIR, HAIR, HAIR, HAIR, HAIR, _MASK, _MASK, _MASK, 
	_MASK, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, SHIRT, SHIRT, RED, 
	SHIRT, SHIRT, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, _MASK, SHIRT, SHIRT, SHIRT, RED, SHIRT, SHIRT, RED, 
	SHIRT, SHIRT, SHIRT, SHIRT, _MASK, SHIRT, SHIRT, SHIRT, SHIRT, RED, RED, RED, RED, SHIRT, SHIRT, SHIRT, 
	SHIRT, SHIRT, SKIN, SKIN, SHIRT, RED, SKIN, RED, RED, SKIN, RED, SHIRT, SKIN, SKIN, SKIN, SKIN, 
	SKIN, SKIN, RED, RED, RED, RED, RED, RED, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, RED, RED, 
	RED, RED, RED, RED, RED, RED, SKIN, SKIN, SKIN, _MASK, _MASK, RED, RED, RED, RED, _MASK, 
	RED, RED, RED, RED, _MASK, _MASK, _MASK, SHOES, SHOES, SHOES, SHOES, _MASK, _MASK, _MASK, SHOES, SHOES, 
	SHOES, SHOES, _MASK, SHOES, SHOES, SHOES, SHOES, SHOES, _MASK, _MASK, _MASK, SHOES, SHOES, SHOES, SHOES, SHOES
};




// const unsigned short MARIO_IDLE[266] ={
// _MASK, _MASK, _MASK, RED, RED, RED, RED, RED, RED, _MASK, _MASK, _MASK, _MASK, _MASK, 
// _MASK, _MASK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, _MASK, 
// _MASK, _MASK, HAIR, HAIR, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, _MASK, _MASK, _MASK, _MASK, 
// _MASK, _MASK, HAIR, HAIR, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, _MASK, _MASK, _MASK, _MASK, 
// _MASK, HAIR, SKIN, HAIR, SKIN, SKIN, SKIN, SKIN, HAIR, SKIN, SKIN, SKIN, SKIN, _MASK, 
// _MASK, HAIR, SKIN, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN, HAIR, SKIN, SKIN, SKIN, SKIN, 
// _MASK, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN, SKIN, HAIR, HAIR, HAIR, HAIR, HAIR, _MASK, 
// _MASK, _MASK, _MASK, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, _MASK, _MASK,
// _MASK, _MASK, WHITE, WHITE, WHITE, RED, WHITE, WHITE, WHITE, _MASK, _MASK, _MASK, _MASK, _MASK, 
// _MASK, WHITE, WHITE, WHITE, WHITE, RED, WHITE, WHITE, RED, WHITE, WHITE, WHITE, WHITE, _MASK, 
// _MASK, WHITE, WHITE, WHITE, WHITE, RED, WHITE, WHITE, RED, WHITE, WHITE, WHITE, WHITE, _MASK, 
// WHITE, WHITE, WHITE, WHITE, WHITE, RED, RED, RED, RED, WHITE, WHITE, WHITE, WHITE, WHITE, 
// SKIN, SKIN, WHITE, RED, RED, SKIN, RED, RED, SKIN, RED, WHITE, WHITE, SKIN, SKIN, 
// SKIN, SKIN, SKIN, RED, RED, RED, RED, RED, RED, RED, SKIN, SKIN, SKIN, SKIN, 
// SKIN, SKIN, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, SKIN, SKIN, 
// _MASK, _MASK, RED, RED, RED, RED, _MASK, _MASK, RED, RED, RED, RED, _MASK, _MASK,
// _MASK, _MASK, RED, RED, RED, RED, _MASK, _MASK, RED, RED, RED, RED, _MASK, _MASK, 
// _MASK, SHOES, SHOES, SHOES, SHOES, _MASK, _MASK, _MASK, _MASK, SHOES, SHOES, SHOES, SHOES, _MASK, 
// SHOES, SHOES, SHOES, SHOES, SHOES, _MASK, _MASK, _MASK, _MASK, SHOES, SHOES, SHOES, SHOES, SHOES};

const byte MARIO_IDLE_SIZE[2]  = {13, 16};


// const unsigned short MARIO_JUMP[361] ={
// _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, SKIN,   // 0x0010 (16) pixels
// SKIN, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, RED, RED, RED, RED, RED, RED,   // 0x0020 (32) pixels
// _MASK, _MASK, SKIN, SKIN, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, RED, RED, RED, RED,   // 0x0030 (48) pixels
// RED, RED, RED, RED, RED, RED, RED, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, HAIR,   // 0x0040 (64) pixels
// HAIR, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, _MASK, SKIN, SKIN, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK,   // 0x0050 (80) pixels
// _MASK, _MASK, HAIR, HAIR, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, _MASK, WHITE, WHITE, WHITE, WHITE, _MASK,   // 0x0060 (96) pixels
// _MASK, _MASK, _MASK, _MASK, HAIR, SKIN, HAIR, SKIN, SKIN, SKIN, SKIN, HAIR, SKIN, SKIN, SKIN, SKIN,   // 0x0070 (112) pixels
// WHITE, WHITE, _MASK, _MASK, _MASK, _MASK, _MASK, HAIR, SKIN, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN, HAIR,   // 0x0080 (128) pixels
// SKIN, SKIN, SKIN, SKIN, WHITE, _MASK, _MASK, _MASK, _MASK, _MASK, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN,   // 0x0090 (144) pixels
// SKIN, HAIR, HAIR, HAIR, HAIR, WHITE, WHITE, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, SKIN,   // 0x00A0 (160) pixels
// SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, SKIN, WHITE, WHITE, _MASK, _MASK, _MASK, _MASK, WHITE, WHITE, WHITE,   // 0x00B0 (176) pixels
// WHITE, WHITE, WHITE, RED, WHITE, WHITE, WHITE, WHITE, RED, WHITE, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK,   // 0x00C0 (192) pixels
// WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, RED, WHITE, WHITE, WHITE, WHITE, RED, WHITE, _MASK, _MASK, _MASK,   // 0x00D0 (208) pixels
// _MASK, _MASK, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, RED, RED, WHITE, WHITE, WHITE, RED,   // 0x00E0 (224) pixels
// _MASK, _MASK, _MASK, SHOES, SKIN, SKIN, SKIN, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, RED, RED, RED,   // 0x00F0 (240) pixels
// RED, RED, RED, _MASK, _MASK, _MASK, SHOES, SKIN, SKIN, SKIN, SKIN, _MASK, RED, RED, WHITE, RED,   // 0x0100 (256) pixels
// RED, RED, SKIN, RED, RED, SKIN, RED, RED, SHOES, SHOES, _MASK, SKIN, SKIN, _MASK, SHOES, RED,   // 0x0110 (272) pixels
// RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, SHOES, SHOES, _MASK, _MASK, SHOES,   // 0x0120 (288) pixels
// SHOES, SHOES, SHOES, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, SHOES, SHOES,   // 0x0130 (304) pixels
// _MASK, _MASK, SHOES, SHOES, SHOES, SHOES, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED,   // 0x0140 (320) pixels
// RED, SHOES, SHOES, _MASK, SHOES, SHOES, SHOES, SHOES, RED, RED, RED, RED, RED, RED, RED, RED,   // 0x0150 (336) pixels
// _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, SHOES, _MASK, _MASK, _MASK, RED, RED, RED, RED, _MASK,   // 0x0160 (352) pixels
// _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK };

// 'mario-jump', 17x16px
const uint16_t MARIO_JUMP [] PROGMEM = {
	_MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, SKIN, SKIN, SKIN, 
	SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, RED, RED, RED, RED, RED, RED, _MASK, SKIN, SKIN, 
	SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, RED, RED, RED, RED, RED, RED, RED, RED, RED, 
	SKIN, SKIN, SKIN, _MASK, _MASK, _MASK, _MASK, _MASK, HAIR, HAIR, HAIR, SKIN, SKIN, HAIR, SKIN, SKIN, 
	SHIRT, SHIRT, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, HAIR, SKIN, HAIR, SKIN, SKIN, SKIN, HAIR, SKIN, 
	SKIN, SHIRT, SHIRT, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, HAIR, SKIN, HAIR, HAIR, SKIN, SKIN, SKIN, 
	HAIR, SKIN, SKIN, SKIN, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, HAIR, HAIR, SKIN, SKIN, SKIN, SKIN, 
	HAIR, HAIR, HAIR, HAIR, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, SKIN, SKIN, SKIN, 
	SKIN, SKIN, SKIN, SKIN, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, RED, 
	SHIRT, SHIRT, SHIRT, RED, SHIRT, SHIRT, _MASK, _MASK, _MASK, _MASK, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, SHIRT, 
	SHIRT, RED, SHIRT, SHIRT, SHIRT, RED, RED, _MASK, SHOES, SHOES, SKIN, SKIN, SHIRT, SHIRT, SHIRT, SHIRT, 
	SHIRT, SHIRT, RED, RED, RED, RED, RED, RED, _MASK, SHOES, SHOES, SKIN, SKIN, SKIN, SKIN, RED, 
	RED, SHIRT, RED, RED, SKIN, RED, RED, SKIN, RED, SHOES, SHOES, SHOES, _MASK, SKIN, SKIN, SHOES, 
	RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, SHOES, SHOES, SHOES, _MASK, _MASK, SHOES, 
	SHOES, SHOES, RED, RED, RED, RED, RED, RED, RED, RED, RED, SHOES, SHOES, SHOES, _MASK, SHOES, 
	SHOES, SHOES, RED, RED, RED, RED, RED, RED, RED, RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, 
	SHOES, SHOES, _MASK, RED, RED, RED, RED, RED, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK, _MASK
};



const byte MARIO_JUMP_SIZE[2]  = {17, 16};



#endif